
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ektha.calculatorservice;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.3.1 2019-05-14T11:31:01.507-05:00
 * Generated source version: 3.3.1
 *
 */

@javax.jws.WebService(serviceName = "CalculatorServiceService", portName = "CalculatorServicePort", targetNamespace = "http://calculatorservice.ektha.com/", wsdlLocation = "file:/C:/bootcampjan2019/development/CoreJava/CalculatorService/WebContent/wsdl/calculatorservice.wsdl", endpointInterface = "com.ektha.calculatorservice.CalculatorService")

public class CalculatorServicePortImpl implements CalculatorService {

	private static final Logger LOG = Logger.getLogger(CalculatorServicePortImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.ektha.calculatorservice.CalculatorService#add(int arg0, int arg1)*
	 */
	@Override
	public int add(int arg0, int arg1) {
		LOG.info("Executing operation add");
		System.out.println(arg0);
		System.out.println(arg1);
		try {
			int _return = -1024583549;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.ektha.calculatorservice.CalculatorService#sub(int arg0, int arg1)*
	 */
	@Override
	public int sub(int arg0, int arg1) {
		LOG.info("Executing operation sub");
		System.out.println(arg0);
		System.out.println(arg1);
		try {
			int _return = 131197803;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
