package com.ektha.calculatorservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-14T11:31:01.547-05:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://calculatorservice.ektha.com/", name = "CalculatorService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculatorService {

    @WebMethod
    @RequestWrapper(localName = "sub", targetNamespace = "http://calculatorservice.ektha.com/", className = "com.ektha.calculatorservice.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://calculatorservice.ektha.com/", className = "com.ektha.calculatorservice.SubResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://calculatorservice.ektha.com/", className = "com.ektha.calculatorservice.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://calculatorservice.ektha.com/", className = "com.ektha.calculatorservice.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
