
package com.ektha.calculatorservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.1 2019-05-14T11:31:01.379-05:00
 * Generated source version: 3.3.1
 *
 */
public final class CalculatorService_CalculatorServicePort_Client {

	private static final QName SERVICE_NAME = new QName("http://calculatorservice.ektha.com/",
			"CalculatorServiceService");

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = CalculatorServiceService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		CalculatorServiceService ss = new CalculatorServiceService(wsdlURL, SERVICE_NAME);
		CalculatorService port = ss.getCalculatorServicePort();

		{
			System.out.println("Invoking sub...");
			int _sub_arg0 = 48;
			int _sub_arg1 = 25;
			int _sub__return = port.sub(_sub_arg0, _sub_arg1);
			System.out.println("sub.result=" + _sub__return);

		}
		{
			System.out.println("Invoking add...");
			int _add_arg0 = 62;
			int _add_arg1 = 59;
			int _add__return = port.add(_add_arg0, _add_arg1);
			System.out.println("add.result=" + _add__return);

		}

		System.exit(0);
	}

	private CalculatorService_CalculatorServicePort_Client() {
	}

}
