<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CalculatorServiceService" targetNamespace="http://calculatorservice.ektha.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://calculatorservice.ektha.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://calculatorservice.ektha.com/" schemaLocation="calculatorservice_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="addResponse">
    <wsdl:part name="parameters" element="tns:addResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sub">
    <wsdl:part name="parameters" element="tns:sub">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="subResponse">
    <wsdl:part name="parameters" element="tns:subResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="add">
    <wsdl:part name="parameters" element="tns:add">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="CalculatorService">
    <wsdl:operation name="sub">
      <wsdl:input name="sub" message="tns:sub">
    </wsdl:input>
      <wsdl:output name="subResponse" message="tns:subResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="add">
      <wsdl:input name="add" message="tns:add">
    </wsdl:input>
      <wsdl:output name="addResponse" message="tns:addResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CalculatorServiceServiceSoapBinding" type="tns:CalculatorService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sub">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sub">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="subResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="add">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="add">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="addResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CalculatorServiceService">
    <wsdl:port name="CalculatorServicePort" binding="tns:CalculatorServiceServiceSoapBinding">
      <soap:address location="http://localhost:8080/CalculatorService/services/CalculatorServicePort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
