
package com.ektha.calculatorservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.1
 * Mon May 13 13:00:52 CDT 2019
 * Generated source version: 3.3.1
 */

@XmlRootElement(name = "subResponse", namespace = "http://calculatorservice.ektha.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subResponse", namespace = "http://calculatorservice.ektha.com/")

public class SubResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

