
package com.ektha.freshdeskwebservices.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.1
 * Wed Apr 17 01:15:39 CDT 2019
 * Generated source version: 3.3.1
 */

@XmlRootElement(name = "getTicketResponse", namespace = "http://service.freshdeskwebservices.ektha.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTicketResponse", namespace = "http://service.freshdeskwebservices.ektha.com/")

public class GetTicketResponse {

    @XmlElement(name = "return")
    private java.util.List<com.ektha.freshdeskwebservices.entity.Ticket> _return;

    public java.util.List<com.ektha.freshdeskwebservices.entity.Ticket> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.ektha.freshdeskwebservices.entity.Ticket> new_return)  {
        this._return = new_return;
    }

}

