
package com.ektha.freshdeskwebservices.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.1
 * Wed Apr 17 01:15:39 CDT 2019
 * Generated source version: 3.3.1
 */

@XmlRootElement(name = "getTicket", namespace = "http://service.freshdeskwebservices.ektha.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTicket", namespace = "http://service.freshdeskwebservices.ektha.com/")

public class GetTicket {


}

