
package com.ektha.freshdeskwebservices.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
/*import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;*/

/**
 * This class was generated by Apache CXF 3.3.1 2019-04-17T23:10:59.717-05:00
 * Generated source version: 3.3.1
 *
 */
public final class TicketService_TicketServicePort_Client {

	private static final QName SERVICE_NAME = new QName("http://service.freshdeskwebservices.ektha.com/",
			"TicketServiceService");

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = TicketServiceService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		TicketServiceService ss = new TicketServiceService(wsdlURL, SERVICE_NAME);
		TicketService port = ss.getTicketServicePort();

		{
			System.out.println("Invoking createTicket...");
			com.ektha.freshdeskwebservices.service.Ticket _createTicket_arg0 = new com.ektha.freshdeskwebservices.service.Ticket();
			_createTicket_arg0.setCategory("Category-988923564");
			_createTicket_arg0.setDescription("Description228109996");
			_createTicket_arg0.setPriority("Priority1432868627");
			_createTicket_arg0.setTitle("Title-258896916");
			int _createTicket__return = port.createTicket(_createTicket_arg0);
			System.out.println("createTicket.result=" + _createTicket__return);

		}
		{
			System.out.println("Invoking getTicket...");
			java.util.List<com.ektha.freshdeskwebservices.service.Ticket> _getTicket__return = port.getTicket();
			System.out.println("getTicket.result=" + _getTicket__return);

		}

		System.exit(0);
	}

	private TicketService_TicketServicePort_Client() {
	}

}
