package com.ektha.freshdeskwebservices.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-17T23:10:59.863-05:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://service.freshdeskwebservices.ektha.com/", name = "TicketService")
@XmlSeeAlso({ObjectFactory.class})
public interface TicketService {

    @WebMethod
    @RequestWrapper(localName = "createTicket", targetNamespace = "http://service.freshdeskwebservices.ektha.com/", className = "com.ektha.freshdeskwebservices.service.CreateTicket")
    @ResponseWrapper(localName = "createTicketResponse", targetNamespace = "http://service.freshdeskwebservices.ektha.com/", className = "com.ektha.freshdeskwebservices.service.CreateTicketResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int createTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ektha.freshdeskwebservices.service.Ticket arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTicket", targetNamespace = "http://service.freshdeskwebservices.ektha.com/", className = "com.ektha.freshdeskwebservices.service.GetTicket")
    @ResponseWrapper(localName = "getTicketResponse", targetNamespace = "http://service.freshdeskwebservices.ektha.com/", className = "com.ektha.freshdeskwebservices.service.GetTicketResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ektha.freshdeskwebservices.service.Ticket> getTicket();
}
