package com.ektha.freshdeskwebservices.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-17T23:10:59.890-05:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "TicketServiceService",
                  wsdlLocation = "file:/C:/bootcampjan2019/development/CoreJava/freshdeskwebservices/src/main/webapp/wsdl/ticketservice.wsdl",
                  targetNamespace = "http://service.freshdeskwebservices.ektha.com/")
public class TicketServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.freshdeskwebservices.ektha.com/", "TicketServiceService");
    public final static QName TicketServicePort = new QName("http://service.freshdeskwebservices.ektha.com/", "TicketServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/bootcampjan2019/development/CoreJava/freshdeskwebservices/src/main/webapp/wsdl/ticketservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TicketServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/bootcampjan2019/development/CoreJava/freshdeskwebservices/src/main/webapp/wsdl/ticketservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TicketServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TicketServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TicketServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TicketServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TicketServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TicketService
     */
    @WebEndpoint(name = "TicketServicePort")
    public TicketService getTicketServicePort() {
        return super.getPort(TicketServicePort, TicketService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketService
     */
    @WebEndpoint(name = "TicketServicePort")
    public TicketService getTicketServicePort(WebServiceFeature... features) {
        return super.getPort(TicketServicePort, TicketService.class, features);
    }

}
