
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ektha.freshdeskwebservices.service;

import java.util.logging.Logger;

/*import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
*/
/**
 * This class was generated by Apache CXF 3.3.1 2019-04-17T23:10:59.819-05:00
 * Generated source version: 3.3.1
 *
 */

@javax.jws.WebService(serviceName = "TicketServiceService", portName = "TicketServicePort", targetNamespace = "http://service.freshdeskwebservices.ektha.com/", wsdlLocation = "file:/C:/bootcampjan2019/development/CoreJava/freshdeskwebservices/src/main/webapp/wsdl/ticketservice.wsdl", endpointInterface = "com.ektha.freshdeskwebservices.service.TicketService")

public class TicketServicePortImpl implements TicketService {

	private static final Logger LOG = Logger.getLogger(TicketServicePortImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.ektha.freshdeskwebservices.service.TicketService#createTicket(com.ektha.
	 * freshdeskwebservices.service.Ticket arg0)*
	 */
	@Override
	public int createTicket(com.ektha.freshdeskwebservices.service.Ticket arg0) {
		LOG.info("Executing operation createTicket");
		System.out.println(arg0);
		try {
			int _return = 261519255;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.ektha.freshdeskwebservices.service.TicketService#getTicket()*
	 */
	@Override
	public java.util.List<com.ektha.freshdeskwebservices.service.Ticket> getTicket() {
		LOG.info("Executing operation getTicket");
		try {
			java.util.List<com.ektha.freshdeskwebservices.service.Ticket> _return = new java.util.ArrayList<com.ektha.freshdeskwebservices.service.Ticket>();
			com.ektha.freshdeskwebservices.service.Ticket _returnVal1 = new com.ektha.freshdeskwebservices.service.Ticket();
			_returnVal1.setCategory("Category572089711");
			_returnVal1.setDescription("Description-762766286");
			_returnVal1.setPriority("Priority-989139251");
			_returnVal1.setTitle("Title1480801907");
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
